spring.application.name=ibm-springboot-demo

server.port=8090

# --- MongoDB ---
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=ibm-ems
spring.data.mongodb.auto-index-creation=true

